config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :users, only: [:show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :line_items
  resources :carts
  resources :store
	resources :books
	resources :categories
  resources :orders


  resources :line_items do
        get 'decrement', on: :member
  end

  resources :orders

  get 'get-cart', action: :get_cart, controller: :carts

	root 'store#index'
  get '/about',   :to => 'store#about'
  get '/privacy',   :to => 'store#privacy'
  get '/contact',   :to => 'store#contact'
  get '/termandcondition',   :to => 'store#termandcondition'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	before_destroy :not_referenced_by_any_line_item
	mount_uploader :image, ImageUploader
	belongs_to :category
	has_many :line_items
	validates :title, presence: true
	validates :author, presence: true
	validates :price, presence: true
	validates :description, presence: true, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}

	validates_processing_of :image
	validate :image_size_validation

	private
	  def image_size_validation
	    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
	  end
    
    private

	  def not_refereced_by_any_line_item
	    unless line_items.empty?
	      errors.add(:base, "Line items present")
	    throw :abort
	  end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show]
  def index
    @books = Book.paginate(:page => params[:page], :per_page => 3)
  end

  def show
  end

  def new
    # @book = current_user.books.build
    @book = Book.new
    # respond_to do |format|
    #   format.html
    # end
  end
  
  def edit
  end

  def create
    # @book = current_user.books.build(book_params)
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.'}
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
    # render plain: book_params.inspect
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        flash[:notice] = 'Book was successfully updated'
        format.html { redirect_to @book, notice: 'Book was successfully updated' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    flash[:success] = 'Book destroyed.'
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :release_year, :price, :description, :isbn, :publisher, :author, :category_id, :image, :remove_image)
  end
end

app/helpers/books_helper.rb
module BooksHelper
	def book_author(book)
    user_signed_in? && current_user.id == book.user_id
  end
end

app/views/books/_form.html.erb
</br>
</br></br></br>
<div class="submit-form">
<%= simple_form_for(@book, html: { multipart: true }) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :category_id, collection: Category.all, label_method: :title, value_method: :id,label: "Category", include_blank: false, prompt: "Select a Category" %>
    <%= f.input :title, :placholder => 'Title' %>   
    <%= f.input :release_year, :placeholder => 'Release Year' %>
    <%= f.input :price, placeholder: 'Enter Price' %>
    <%= f.input :description, placeholder: 'description' %> 
    <%= f.input :author, placeholder: 'author' %>
    <%= f.input :isbn %>
    <%= f.input :publisher %> 
    <%= f.label "Upload Image" %>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>  
    <%= f.button :submit %>          
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>
<button><%= link_to 'Show', @book %></button> |
<button><%= link_to 'Back', books_path %></button>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>
 <% form_tag books_path, :method => :get do %>
  <p>
    <% text_field_tag :search, params[:search] %>
    <% submit_tag "Search" %>
  </p>
<% end %>
<button><%= link_to 'New Book', new_book_path %></button>
<table>
  <tbody>
    <% @books.each do |book| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <% if book.image.present? %>
            <%= image_tag book.image.thumb.url, class: "list_image" %>
          <% else %>
            <img class="card-img-top" src="http://placehold.it/100x150" alt="Card image cap">
          <% end %>
        </td>
        <td class="list_description">
          <dl>
            <dt><%= book.title %></dt>
            <dd><b>Price: </b><%= book.price %></dd>
            <dd><b>Description: </b><%= truncate(strip_tags(book.description), length: 80) %></dd>
            <dd><b>Year: </b><%= book.release_year %></dd>
            <dd><b>ISBN: </b><%= book.isbn %></dd>
            <dd><b>Author: </b><%= book.author %></dd>
            <dd><b>Publisher: </b><%= book.publisher %></dd>
            <dd><b>Category: </b><%= book.category.title %></dd>
          </dl>
        </td>
        <td class="list_actions">
          <%= link_to 'Show', book %><br>
          <%= link_to 'Edit', edit_book_path(book) %><br>
          <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %>

          <%= button_to 'Add to cart', line_items_path(book_id: book), class: 'btn btn-default' %>
        </td>
      </tr>
    <% end %>
    <hr>
  </tbody>
</table>
<%= will_paginate @books %>
<%= render "carts/cart"%>

app/views/books/new.html.erb
<h1><center>New Book</center></h1>
<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<% if @book.image.present? %>
  <%= image_tag @book.image.thumb.url %>
<% else %>
  <img class="card-img-top" src="http://placehold.it/200x300" alt="Card image cap">
<% end %>
    <p>
      <strong>Category:</strong>
      <%= @book.category.title %>
    </p>
    <p>
      <strong>Title:</strong>
      <%= @book.title %>
    </p>
    <p>
      <strong>Release Year:</strong>
      <%= @book.release_year %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @book.description %>
    </p>
    <p>
      <strong>Price:</strong>
      <%= @book.price %>
    </p>
    <p>
      <strong>ISBN:</strong>
      <%= @book.isbn %>
    </p>
    <p>
      <strong>Publiser:</strong>
      <%= @book.publisher %>
    </p>
    <p>
      <strong>Author:</strong>
      <%= @book.author %>
    </p>

    <h4><%= number_to_currency(@book.price) %></h4>
    <%= form_tag(line_items_path(book_id: @book), remote: true, class: "form-inline") do %>
      Quantity: 
      <%= select_tag "quantity", options_for_select(1..10), class: "from-control" %>&nbsp;
      <%= submit_tag 'Add to cart', class: 'btn btn-success', id: @book.id %>
    <% end %>

    <%= link_to 'Edit', edit_book_path(@book), class: 'button' %>