config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :users, only: [:show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :line_items
  resources :carts
  resources :store
	resources :books
	resources :categories
  resources :orders


  resources :line_items do
        get 'decrement', on: :member
  end

  resources :orders

  get 'get-cart', action: :get_cart, controller: :carts

	root 'store#index'
  get '/about',   :to => 'store#about'
  get '/privacy',   :to => 'store#privacy'
  get '/contact',   :to => 'store#contact'
  get '/termandcondition',   :to => 'store#termandcondition'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
  has_one :user

 def add_book(book, quantity=1)
  current_item = line_items.find_by(book_id: book.id)
  if current_item
    current_quantity = current_item.quantity
    quantity = current_quantity.to_i + quantity.to_i
    current_item.update_attribute(:quantity, quantity)
  else
    current_item = line_items.build(book_id: book.id, quantity: quantity)
  end
  current_item
 end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # def destroy
  #   @cart.destroy if @cart.id == session[:cart_id]
  #   session[:cart_id] = nil
  #   flash[:info] = 'Cart was successfully destroyed.'
  #   respond_to do |format|
  #     format.html { redirect_to root_path }
  #     format.json { head :no_content }
  #   end
  # end


  def destroy
    if @cart.id == session[:cart_id]
      @cart.destroy 
      session[:cart_id] = nil
      flash[:info] = 'Cart was successfully destroyed.'

    elsif @cart.id == current_user[:cart_id]
      @cart.destroy
      current_user[:cart_id] = nil
      current_user.save
      flash[:info] = 'Your personal Cart was successfully destroyed.'
    end
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json{ head :no_content }
    end
  end


  def get_cart
    
  end


  private
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% if @cart.line_items.present? %>
	<h5 align="center" class="text-muted">Your cart</h5>
	<table class="table table-condensed">

		<thead>
			<tr>
				<th>Product</th>
				<th>Quantity</th>
				<th>Price</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @cart.line_items.each do |line_item| %>
				<tr>
				  <td><%= line_item.book.title %></td>
				  <td style="text-align: center;"><%= line_item.quantity %></td>
				  <td><%= number_to_currency(line_item.total_price) %></td>
				  <td><%= link_to image_tag("delete4.png"), decrement_line_item_path(id: line_item.id), class: "link-img", remote: true %></td>
				</tr>
			<% end %>
		</tbody>
	</table><hr>

	<h5 align="center" class="text-muted">
		Total: <%= number_to_currency(@cart.total_price) %>
	</h5><hr>
	<h1 align="right">	
		<%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-warning" %>
	</h1>
<% else %>
	<p class="text-muted">Your cart is empty!</p>
<% end %>

app/views/carts/_cart_badge.html.erb
<%= @cart.line_items.present? ? @cart.line_items.count : "" %>

app/views/carts/_cart_modal.html.erb
<div class="modal-dialog modal-dialog-centered modal-lg">
  <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
      <div id="cart-update" class="modal-body">
        <% if @cart.line_items.present? %>
          <h5 align="center" class="text-muted">Your cart</h5>
          <table class="table table-condensed">
            <thead>
              <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th></th>
              </tr>
            </thead>
            <tbody id="cart-table">
              <% @cart.line_items.each do |line_item| %>
                <tr id="line_<%= line_item.id %>">
                  <td><%= link_to line_item.book.title, line_item.book %></td>
                  <td class="quantity"><%= line_item.quantity %></td>
                  <td><%= number_to_currency(line_item.total_price) %></td>
                  <td><%= link_to image_tag("delete4.png"), decrement_line_item_path(id: line_item.id), class: "link-img", remote: true %></td>
                </tr>
              <% end %>
            </tbody>
          </table><hr>

          <h5 id="total" align="center" class="text-muted">
            Total: <%= number_to_currency(@cart.total_price) %>
          </h5><hr>

          <center>
            <%= link_to 'Checkout', new_order_path(cart_id: @cart.id), class: "btn btn-success" %> &nbsp;
            <%= link_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-warning", id: "empty-btn" %>
          </center>
        <% else %>
          <p id="no-quantity" class="text-muted">Your cart is empty!</p>
        <% end %>

      </div>
      <div class="modal-footer">
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
  </div>
</div>

<style type="text/css">
  .cart-img {
    width: 100px;
    height: 150px;
  }
</style>

app/views/carts/get_cart.js.erb
$("#cart-modal").html("<%= escape_javascript(render "cart_modal") %>");
$("#cart-modal").modal("show");

app/views/carts/show.html.erb
<div class="keep-shopping pv1 mt4 has-text-right">
  <%= link_to 'Keep Shopping', books_path, class: 'button is-warning' %>
</div>
<hr />
<section class="section">
  <%= render(@cart.line_items) %>

  <div class="columns">
    <div class="column">
      <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>
    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4">
        <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
      </h4>
    </div>
  </div>
</section>