config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :users, only: [:show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :line_items
  resources :carts
  resources :store
	resources :books
	resources :categories
  resources :orders


  resources :line_items do
        get 'decrement', on: :member
  end

  resources :orders

  get 'get-cart', action: :get_cart, controller: :carts

	root 'store#index'
  get '/about',   :to => 'store#about'
  get '/privacy',   :to => 'store#privacy'
  get '/contact',   :to => 'store#contact'
  get '/termandcondition',   :to => 'store#termandcondition'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
	validates :title, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		redirect_to categories_path, notice: "Created Successfully"
  	else
  		render 'new'
  	end
  end

  def edit
  	@category = Category.find(params[:id])
  end
  
  def update
  	@category = Category.find(params[:id])
  	if @category.update_attributes(category_params)
  		redirect_to categories_path, notice: "Updated Successfully"
  	else
  		render "edit"
  	end
  end

  def destroy
  	@category = Category.find(params[:id])
  	if @category.destroy
  		redirect_to categories_path, notice: "Deleted category"
  	end
  end

  private

  def category_params
  	params.require(:category).permit(:title)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="submit-form">
<%= simple_form_for(@category, :wrapper => :horizontal_form) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :title, :placholder => 'Title' %>   
    <%= f.button :submit %>          
<% end %>

app/views/categories/edit.html.erb
<h3>Edit Category</h3>
<%= render 'form' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Categories List</h3>
<table class="table table-striped">
	<th>Title</th>
	<th></th>
	<th></th>
	<tbody>
		<% @categories.each do |category| %>
		<tr>
			<td><%= category.title %></td>
			<td><%= link_to "Edit", edit_category_path(category) %></td>
			<td><%= link_to "Delete", category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "New Category", new_category_path %>

app/views/categories/new.html.erb
<h3>New Category</h3>
<%= render 'form' %>