config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :users, only: [:show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :line_items
  resources :carts
  resources :store
	resources :books
	resources :categories
  resources :orders


  resources :line_items do
        get 'decrement', on: :member
  end

  resources :orders

  get 'get-cart', action: :get_cart, controller: :carts

	root 'store#index'
  get '/about',   :to => 'store#about'
  get '/privacy',   :to => 'store#privacy'
  get '/contact',   :to => 'store#contact'
  get '/termandcondition',   :to => 'store#termandcondition'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	before_destroy :not_referenced_by_any_line_item
	mount_uploader :image, ImageUploader
	belongs_to :category
	has_many :line_items
	validates :title, presence: true
	validates :author, presence: true
	validates :price, presence: true
	validates :description, presence: true, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}

	validates_processing_of :image
	validate :image_size_validation

	private
	  def image_size_validation
	    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
	  end
    
    private

	  def not_refereced_by_any_line_item
	    unless line_items.empty?
	      errors.add(:base, "Line items present")
	    throw :abort
	  end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
  has_one :user

 def add_book(book, quantity=1)
  current_item = line_items.find_by(book_id: book.id)
  if current_item
    current_quantity = current_item.quantity
    quantity = current_quantity.to_i + quantity.to_i
    current_item.update_attribute(:quantity, quantity)
  else
    current_item = line_items.build(book_id: book.id, quantity: quantity)
  end
  current_item
 end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
	validates :title, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :cart


  belongs_to :order, optional: true

  def total_price
  	book.price.to_i * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items
	belongs_to :user

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :cart, optional: true
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show]
  def index
    @books = Book.paginate(:page => params[:page], :per_page => 3)
  end

  def show
  end

  def new
    # @book = current_user.books.build
    @book = Book.new
    # respond_to do |format|
    #   format.html
    # end
  end
  
  def edit
  end

  def create
    # @book = current_user.books.build(book_params)
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.'}
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
    # render plain: book_params.inspect
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        flash[:notice] = 'Book was successfully updated'
        format.html { redirect_to @book, notice: 'Book was successfully updated' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    flash[:success] = 'Book destroyed.'
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :release_year, :price, :description, :isbn, :publisher, :author, :category_id, :image, :remove_image)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # def destroy
  #   @cart.destroy if @cart.id == session[:cart_id]
  #   session[:cart_id] = nil
  #   flash[:info] = 'Cart was successfully destroyed.'
  #   respond_to do |format|
  #     format.html { redirect_to root_path }
  #     format.json { head :no_content }
  #   end
  # end


  def destroy
    if @cart.id == session[:cart_id]
      @cart.destroy 
      session[:cart_id] = nil
      flash[:info] = 'Cart was successfully destroyed.'

    elsif @cart.id == current_user[:cart_id]
      @cart.destroy
      current_user[:cart_id] = nil
      current_user.save
      flash[:info] = 'Your personal Cart was successfully destroyed.'
    end
    respond_to do |format|
      format.html {redirect_to root_path}
      format.json{ head :no_content }
    end
  end


  def get_cart
    
  end


  private
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
  	@orders = Order.all
  end

  def new
  	@cart = Cart.find(params[:cart_id])
	  @order = Order.new
  end

  def create
  	@order = current_user.orders.new()
    @order.add_line_items_from_cart(@cart)
    if @order.save
      redirect_to store_index_path, notice: "thanks for your order"
    else
      redirect_to store_index_path, notice: @order.errors
    end
  end

  private

  def order_params
 	params.require(:order).permit(:user_id, :pay_type)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  # before_action :authenticate_user!

  def index
  	if params[:category_id]
  		category_id = params[:category_id]
  		category = Category.find(category_id)
  		@books = category.books.paginate(:page => params[:page], :per_page => 12)
  	else
	  	@books = Book.paginate(:page => params[:page], :per_page => 12)
	end
  	@categories = Category.all
  end


  def show
  	@book = Book.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# helper_method :resource_name, :resource, :devise_mapping, :resource_class

	  def resource_name
	    :user
	  end
	 
	  def resource
	    @resource ||= User.new
	  end

	  def resource_class
	    User
	  end
	 
	  def devise_mapping
	    @devise_mapping ||= Devise.mappings[:user]
	  end

	
	def cart_count_over_one
	    if @cart.line_items.count > 0
	      return "<span class='tag is-dark'>#{@cart.line_items.count}</span>".html_safe
	    end
	end

  def cart_has_items
    return @cart.line_items.count > 0
  end

end

app/helpers/books_helper.rb
module BooksHelper
	def book_author(book)
    user_signed_in? && current_user.id == book.user_id
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
  	<div class="row">
      <div class="links">
        <div class="block-title">
          <strong>
    	      <span>Company</span>
          </strong>
        </div>
        <ul class="list-unstyled">
  	      <li><%= link_to 'About Us', about_path%></li>
  	      <li><%= link_to 'Contact Us', contact_path%></li>
  	      <li><%= link_to 'Privacy Policy', privacy_path%></li>
  	      <li><%= link_to 'Terms And Conditions', termandcondition_path%></li>
        <ul>
      </div>
      <pre></pre>
      <div class="links">
        <div class="block-title">
          <strong>
    	      <span>Quick Links</span>
          </strong>
        </div>
        <ul class="list-unstyled">
  	      <li><a href="#">Site Map</li>
  	      <li><a href="#">Search Terms</li>
  	      <li><a href="#">Order and Returns</li>
        <ul>
      </div>
    </div>
  </div>
  <div class="copyright-bar">
  	<div class="container">
  		<div class="no-padding social">
  			<ul class="card">
  				<p>PAYMENT METHOD</p>
  				<li>
  					<%= image_tag("img1.png",:style=>"height:2vw; width:2vw;") %>
  					<%= image_tag("img2.png",:style=>"height:2vw; width:2vw;") %>
  					<%= image_tag("img3.jpg",:style=>"height:2vw; width:2vw;") %>
  			  </li>
  			</ul>
  		</div>
  		<div class="payment-methodes">
  			<ul class="soc-icon">
  				<div class="com-name ">Follow Us:</div>
  				<li>
  					<a target="_blank" href="https://www.facebook.com/booksearch.com" title="Facebook Booksearch">
  					</a>
  		
  					<a target="_blank" href="https://www.twitter.com/booksearch.com" title="Facebook Booksearch">
  					</a>
  					<%= image_tag("twitter.jpg") %>

  					<a target="_blank" href="https://www.linkedin.com/booksearch.com" title="Facebook Booksearch">
  					</a>
  					<%= image_tag("linked.png",:style=>"height:2vw; width:2vw;") %>
  				</li>
  			</ul>
  		</div>
  	</div>
  	<center><address>@ 2018 BookSearch.com All Rights Reserved.</address></center>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">BOOKSEARCH<%= fa_icon "shopping-cart 2x" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <%= link_to "Admin", admin_root_path, target: :_blank %>
      </li>
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu mega-menu" aria-labelledby="navbarDropdown">
          <div class="row">
            <% @categories.take(6).each do |category| %>
              <div class="col-md-2">
              <strong class="sub-menu-heading"><%= category.title %></strong><hr>
                <% category.books.take(5).each do |book| %>
                  <%= link_to book.title, book, class: "book-link-nav" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </li>
      <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>  
    </p>
    </ul>
    
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to get_cart_path, remote: true, class: "nav-link" do %>
          <%= fa_icon "shopping-cart 2x" %>
          <span id="cart-badge" class="badge badge-warning"><%= @cart.line_items.present? ? @cart.line_items.count : "" %></span>
        <% end %>
      </li>
      &nbsp;&nbsp;
      <li class="nav-item">
        <% if current_user %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>&nbsp;&nbsp;
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Welcome, <%= current_user.name %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>       
    </ul>
  </div>
</nav>

<style type="text/css">
  a.book-link-nav {
    color:red;
    display: block;
  }

  .badge {
    position: absolute;
    margin: -40px 32px;
  }
</style>

<script type="text/javascript">
  $('div.dropdown-menu').on('click', function(event){
    // The event won't be propagated up to the document NODE and 
    // therefore delegated events won't be fired
    event.stopPropagation();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booksearch</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |key, value| %>
      <div style="text-align: center;" class="alert alert-<%= key %>">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= value %>
      </div>
    <% end %>
    <div id="login-modal" class="modal fade"></div>
    <div id="cart-modal" class="modal fade"></div>
    <div class="container-fluid">
      
      <%= render 'layouts/nav' %>
      <%= yield %>
    </div>
  </body>
</html>